# Generated by Django 4.1.7 on 2023-02-28 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemon_evolved_from_pokemon_evolved_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolved_to',
            new_name='next_evolution',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='evolved_from',
            new_name='previous_evolution',
        ),
    ]
